const reviews = [
    {
      id: 1,
      model: 'Vauxhall Corsa 2014',
      price: '£5,000',
      image:'https://www.pngkit.com/png/full/837-8373715_another-stalwart-of-the-small-car-sector-the.png',
      title: 'specifications',
      engine: 'Engine size | 1.4L',
      speed: 'Top Speed | 120mph',
      power: 'Engine Power | 74bhp',
      mot: 'M.O.T Expires: 12th November 2021',
      mileage: 'Mileage | 15,000',
    },
    {
      id: 2,
      model: 'Ford KA+ 2019',
      price: '£6,790',
      image:'https://4.bp.blogspot.com/-sXj2roya29I/Ww8oWhJwTMI/AAAAAAACRew/3WXzPLAlxo89ontr4Hid9INhU-chy-L6wCLcBGAs/s1600/Ka.png',
      title: 'specifications',
      engine: 'Engine size | 1.2L',
      speed: 'Top Speed | 105mph',
      power: 'Engine Power | 84bhp',
      mot: 'M.O.T Expires: 2nd February 2022',
      mileage: 'Mileage | 22,608',
    },
    {
      id: 3,
      model: 'Seat Ibiza 2010',
      price: '£2,450',
      image:'https://fuse-box.info/wp-content/uploads/2018/02/Seat-Ibiza-Mk4_6J-2008-2015.jpg',
      title: 'specifications',
      engine: 'Engine size | 1.4L',
      speed: 'Top Speed | 108mph',
      power: 'Engine Power | 84bhp',
      mot: 'M.O.T Expires: 19th December 2021',
      mileage: 'Mileage | 50,225',
    },
    {
      id: 4,
      model: 'Peugueot 207 2009',
      price: '£1,552',
      image:'https://mediacloud.carbuyer.co.uk/image/private/s--Odn6xr-o--/v1579599206/carbuyer/Peugeot_207.jpg',
      title: 'specifications',
      engine: 'Engine size | 1.6L',
      speed: 'Top Speed | 122mph',
      power: 'Engine Power | 120bhp',
      mot: 'M.O.T Expires: 7th October 2021',
      mileage: 'Mileage | 46,000',
    },
  ];
  
  export default reviews;